# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gcp.longrunning import operations_pb2 as gcp_dot_longrunning_dot_operations__pb2
from service import gcp_asr_v2_pb2 as service_dot_gcp__asr__v2__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service/gcp_asr_v2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpeechStub(object):
    """Enables speech transcription and resource management.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRecognizer = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/CreateRecognizer',
                request_serializer=service_dot_gcp__asr__v2__pb2.CreateRecognizerRequest.SerializeToString,
                response_deserializer=gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.ListRecognizers = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/ListRecognizers',
                request_serializer=service_dot_gcp__asr__v2__pb2.ListRecognizersRequest.SerializeToString,
                response_deserializer=service_dot_gcp__asr__v2__pb2.ListRecognizersResponse.FromString,
                _registered_method=True)
        self.GetRecognizer = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/GetRecognizer',
                request_serializer=service_dot_gcp__asr__v2__pb2.GetRecognizerRequest.SerializeToString,
                response_deserializer=service_dot_gcp__asr__v2__pb2.Recognizer.FromString,
                _registered_method=True)
        self.UpdateRecognizer = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/UpdateRecognizer',
                request_serializer=service_dot_gcp__asr__v2__pb2.UpdateRecognizerRequest.SerializeToString,
                response_deserializer=gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.DeleteRecognizer = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/DeleteRecognizer',
                request_serializer=service_dot_gcp__asr__v2__pb2.DeleteRecognizerRequest.SerializeToString,
                response_deserializer=gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.UndeleteRecognizer = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/UndeleteRecognizer',
                request_serializer=service_dot_gcp__asr__v2__pb2.UndeleteRecognizerRequest.SerializeToString,
                response_deserializer=gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.Recognize = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/Recognize',
                request_serializer=service_dot_gcp__asr__v2__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=service_dot_gcp__asr__v2__pb2.RecognizeResponse.FromString,
                _registered_method=True)
        self.StreamingRecognize = channel.stream_stream(
                '/google.cloud.speech.v2.Speech/StreamingRecognize',
                request_serializer=service_dot_gcp__asr__v2__pb2.StreamingRecognizeRequest.SerializeToString,
                response_deserializer=service_dot_gcp__asr__v2__pb2.StreamingRecognizeResponse.FromString,
                _registered_method=True)
        self.BatchRecognize = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/BatchRecognize',
                request_serializer=service_dot_gcp__asr__v2__pb2.BatchRecognizeRequest.SerializeToString,
                response_deserializer=gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/GetConfig',
                request_serializer=service_dot_gcp__asr__v2__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=service_dot_gcp__asr__v2__pb2.Config.FromString,
                _registered_method=True)
        self.UpdateConfig = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/UpdateConfig',
                request_serializer=service_dot_gcp__asr__v2__pb2.UpdateConfigRequest.SerializeToString,
                response_deserializer=service_dot_gcp__asr__v2__pb2.Config.FromString,
                _registered_method=True)
        self.CreateCustomClass = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/CreateCustomClass',
                request_serializer=service_dot_gcp__asr__v2__pb2.CreateCustomClassRequest.SerializeToString,
                response_deserializer=gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.ListCustomClasses = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/ListCustomClasses',
                request_serializer=service_dot_gcp__asr__v2__pb2.ListCustomClassesRequest.SerializeToString,
                response_deserializer=service_dot_gcp__asr__v2__pb2.ListCustomClassesResponse.FromString,
                _registered_method=True)
        self.GetCustomClass = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/GetCustomClass',
                request_serializer=service_dot_gcp__asr__v2__pb2.GetCustomClassRequest.SerializeToString,
                response_deserializer=service_dot_gcp__asr__v2__pb2.CustomClass.FromString,
                _registered_method=True)
        self.UpdateCustomClass = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/UpdateCustomClass',
                request_serializer=service_dot_gcp__asr__v2__pb2.UpdateCustomClassRequest.SerializeToString,
                response_deserializer=gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.DeleteCustomClass = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/DeleteCustomClass',
                request_serializer=service_dot_gcp__asr__v2__pb2.DeleteCustomClassRequest.SerializeToString,
                response_deserializer=gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.UndeleteCustomClass = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/UndeleteCustomClass',
                request_serializer=service_dot_gcp__asr__v2__pb2.UndeleteCustomClassRequest.SerializeToString,
                response_deserializer=gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.CreatePhraseSet = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/CreatePhraseSet',
                request_serializer=service_dot_gcp__asr__v2__pb2.CreatePhraseSetRequest.SerializeToString,
                response_deserializer=gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.ListPhraseSets = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/ListPhraseSets',
                request_serializer=service_dot_gcp__asr__v2__pb2.ListPhraseSetsRequest.SerializeToString,
                response_deserializer=service_dot_gcp__asr__v2__pb2.ListPhraseSetsResponse.FromString,
                _registered_method=True)
        self.GetPhraseSet = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/GetPhraseSet',
                request_serializer=service_dot_gcp__asr__v2__pb2.GetPhraseSetRequest.SerializeToString,
                response_deserializer=service_dot_gcp__asr__v2__pb2.PhraseSet.FromString,
                _registered_method=True)
        self.UpdatePhraseSet = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/UpdatePhraseSet',
                request_serializer=service_dot_gcp__asr__v2__pb2.UpdatePhraseSetRequest.SerializeToString,
                response_deserializer=gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.DeletePhraseSet = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/DeletePhraseSet',
                request_serializer=service_dot_gcp__asr__v2__pb2.DeletePhraseSetRequest.SerializeToString,
                response_deserializer=gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.UndeletePhraseSet = channel.unary_unary(
                '/google.cloud.speech.v2.Speech/UndeletePhraseSet',
                request_serializer=service_dot_gcp__asr__v2__pb2.UndeletePhraseSetRequest.SerializeToString,
                response_deserializer=gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)


class SpeechServicer(object):
    """Enables speech transcription and resource management.
    """

    def CreateRecognizer(self, request, context):
        """Creates a [Recognizer][google.cloud.speech.v2.Recognizer].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRecognizers(self, request, context):
        """Lists Recognizers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecognizer(self, request, context):
        """Returns the requested
        [Recognizer][google.cloud.speech.v2.Recognizer]. Fails with
        [NOT_FOUND][google.rpc.Code.NOT_FOUND] if the requested Recognizer doesn't
        exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRecognizer(self, request, context):
        """Updates the [Recognizer][google.cloud.speech.v2.Recognizer].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRecognizer(self, request, context):
        """Deletes the [Recognizer][google.cloud.speech.v2.Recognizer].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UndeleteRecognizer(self, request, context):
        """Undeletes the [Recognizer][google.cloud.speech.v2.Recognizer].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recognize(self, request, context):
        """Performs synchronous Speech recognition: receive results after all audio
        has been sent and processed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamingRecognize(self, request_iterator, context):
        """Performs bidirectional streaming speech recognition: receive results while
        sending audio. This method is only available via the gRPC API (not REST).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchRecognize(self, request, context):
        """Performs batch asynchronous speech recognition: send a request with N
        audio files and receive a long running operation that can be polled to see
        when the transcriptions are finished.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Returns the requested [Config][google.cloud.speech.v2.Config].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """Updates the [Config][google.cloud.speech.v2.Config].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCustomClass(self, request, context):
        """Creates a [CustomClass][google.cloud.speech.v2.CustomClass].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCustomClasses(self, request, context):
        """Lists CustomClasses.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustomClass(self, request, context):
        """Returns the requested
        [CustomClass][google.cloud.speech.v2.CustomClass].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCustomClass(self, request, context):
        """Updates the [CustomClass][google.cloud.speech.v2.CustomClass].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCustomClass(self, request, context):
        """Deletes the [CustomClass][google.cloud.speech.v2.CustomClass].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UndeleteCustomClass(self, request, context):
        """Undeletes the [CustomClass][google.cloud.speech.v2.CustomClass].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePhraseSet(self, request, context):
        """Creates a [PhraseSet][google.cloud.speech.v2.PhraseSet].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPhraseSets(self, request, context):
        """Lists PhraseSets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPhraseSet(self, request, context):
        """Returns the requested
        [PhraseSet][google.cloud.speech.v2.PhraseSet].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePhraseSet(self, request, context):
        """Updates the [PhraseSet][google.cloud.speech.v2.PhraseSet].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePhraseSet(self, request, context):
        """Deletes the [PhraseSet][google.cloud.speech.v2.PhraseSet].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UndeletePhraseSet(self, request, context):
        """Undeletes the [PhraseSet][google.cloud.speech.v2.PhraseSet].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRecognizer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRecognizer,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.CreateRecognizerRequest.FromString,
                    response_serializer=gcp_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'ListRecognizers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRecognizers,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.ListRecognizersRequest.FromString,
                    response_serializer=service_dot_gcp__asr__v2__pb2.ListRecognizersResponse.SerializeToString,
            ),
            'GetRecognizer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecognizer,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.GetRecognizerRequest.FromString,
                    response_serializer=service_dot_gcp__asr__v2__pb2.Recognizer.SerializeToString,
            ),
            'UpdateRecognizer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRecognizer,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.UpdateRecognizerRequest.FromString,
                    response_serializer=gcp_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteRecognizer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRecognizer,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.DeleteRecognizerRequest.FromString,
                    response_serializer=gcp_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UndeleteRecognizer': grpc.unary_unary_rpc_method_handler(
                    servicer.UndeleteRecognizer,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.UndeleteRecognizerRequest.FromString,
                    response_serializer=gcp_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.RecognizeRequest.FromString,
                    response_serializer=service_dot_gcp__asr__v2__pb2.RecognizeResponse.SerializeToString,
            ),
            'StreamingRecognize': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamingRecognize,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.StreamingRecognizeRequest.FromString,
                    response_serializer=service_dot_gcp__asr__v2__pb2.StreamingRecognizeResponse.SerializeToString,
            ),
            'BatchRecognize': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchRecognize,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.BatchRecognizeRequest.FromString,
                    response_serializer=gcp_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.GetConfigRequest.FromString,
                    response_serializer=service_dot_gcp__asr__v2__pb2.Config.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.UpdateConfigRequest.FromString,
                    response_serializer=service_dot_gcp__asr__v2__pb2.Config.SerializeToString,
            ),
            'CreateCustomClass': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCustomClass,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.CreateCustomClassRequest.FromString,
                    response_serializer=gcp_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'ListCustomClasses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCustomClasses,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.ListCustomClassesRequest.FromString,
                    response_serializer=service_dot_gcp__asr__v2__pb2.ListCustomClassesResponse.SerializeToString,
            ),
            'GetCustomClass': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomClass,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.GetCustomClassRequest.FromString,
                    response_serializer=service_dot_gcp__asr__v2__pb2.CustomClass.SerializeToString,
            ),
            'UpdateCustomClass': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCustomClass,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.UpdateCustomClassRequest.FromString,
                    response_serializer=gcp_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteCustomClass': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCustomClass,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.DeleteCustomClassRequest.FromString,
                    response_serializer=gcp_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UndeleteCustomClass': grpc.unary_unary_rpc_method_handler(
                    servicer.UndeleteCustomClass,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.UndeleteCustomClassRequest.FromString,
                    response_serializer=gcp_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'CreatePhraseSet': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePhraseSet,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.CreatePhraseSetRequest.FromString,
                    response_serializer=gcp_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'ListPhraseSets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPhraseSets,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.ListPhraseSetsRequest.FromString,
                    response_serializer=service_dot_gcp__asr__v2__pb2.ListPhraseSetsResponse.SerializeToString,
            ),
            'GetPhraseSet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPhraseSet,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.GetPhraseSetRequest.FromString,
                    response_serializer=service_dot_gcp__asr__v2__pb2.PhraseSet.SerializeToString,
            ),
            'UpdatePhraseSet': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePhraseSet,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.UpdatePhraseSetRequest.FromString,
                    response_serializer=gcp_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeletePhraseSet': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePhraseSet,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.DeletePhraseSetRequest.FromString,
                    response_serializer=gcp_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UndeletePhraseSet': grpc.unary_unary_rpc_method_handler(
                    servicer.UndeletePhraseSet,
                    request_deserializer=service_dot_gcp__asr__v2__pb2.UndeletePhraseSetRequest.FromString,
                    response_serializer=gcp_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.cloud.speech.v2.Speech', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('google.cloud.speech.v2.Speech', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Speech(object):
    """Enables speech transcription and resource management.
    """

    @staticmethod
    def CreateRecognizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/CreateRecognizer',
            service_dot_gcp__asr__v2__pb2.CreateRecognizerRequest.SerializeToString,
            gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRecognizers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/ListRecognizers',
            service_dot_gcp__asr__v2__pb2.ListRecognizersRequest.SerializeToString,
            service_dot_gcp__asr__v2__pb2.ListRecognizersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecognizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/GetRecognizer',
            service_dot_gcp__asr__v2__pb2.GetRecognizerRequest.SerializeToString,
            service_dot_gcp__asr__v2__pb2.Recognizer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRecognizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/UpdateRecognizer',
            service_dot_gcp__asr__v2__pb2.UpdateRecognizerRequest.SerializeToString,
            gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRecognizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/DeleteRecognizer',
            service_dot_gcp__asr__v2__pb2.DeleteRecognizerRequest.SerializeToString,
            gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UndeleteRecognizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/UndeleteRecognizer',
            service_dot_gcp__asr__v2__pb2.UndeleteRecognizerRequest.SerializeToString,
            gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/Recognize',
            service_dot_gcp__asr__v2__pb2.RecognizeRequest.SerializeToString,
            service_dot_gcp__asr__v2__pb2.RecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamingRecognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/google.cloud.speech.v2.Speech/StreamingRecognize',
            service_dot_gcp__asr__v2__pb2.StreamingRecognizeRequest.SerializeToString,
            service_dot_gcp__asr__v2__pb2.StreamingRecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchRecognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/BatchRecognize',
            service_dot_gcp__asr__v2__pb2.BatchRecognizeRequest.SerializeToString,
            gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/GetConfig',
            service_dot_gcp__asr__v2__pb2.GetConfigRequest.SerializeToString,
            service_dot_gcp__asr__v2__pb2.Config.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/UpdateConfig',
            service_dot_gcp__asr__v2__pb2.UpdateConfigRequest.SerializeToString,
            service_dot_gcp__asr__v2__pb2.Config.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCustomClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/CreateCustomClass',
            service_dot_gcp__asr__v2__pb2.CreateCustomClassRequest.SerializeToString,
            gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCustomClasses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/ListCustomClasses',
            service_dot_gcp__asr__v2__pb2.ListCustomClassesRequest.SerializeToString,
            service_dot_gcp__asr__v2__pb2.ListCustomClassesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCustomClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/GetCustomClass',
            service_dot_gcp__asr__v2__pb2.GetCustomClassRequest.SerializeToString,
            service_dot_gcp__asr__v2__pb2.CustomClass.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCustomClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/UpdateCustomClass',
            service_dot_gcp__asr__v2__pb2.UpdateCustomClassRequest.SerializeToString,
            gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCustomClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/DeleteCustomClass',
            service_dot_gcp__asr__v2__pb2.DeleteCustomClassRequest.SerializeToString,
            gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UndeleteCustomClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/UndeleteCustomClass',
            service_dot_gcp__asr__v2__pb2.UndeleteCustomClassRequest.SerializeToString,
            gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePhraseSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/CreatePhraseSet',
            service_dot_gcp__asr__v2__pb2.CreatePhraseSetRequest.SerializeToString,
            gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPhraseSets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/ListPhraseSets',
            service_dot_gcp__asr__v2__pb2.ListPhraseSetsRequest.SerializeToString,
            service_dot_gcp__asr__v2__pb2.ListPhraseSetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPhraseSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/GetPhraseSet',
            service_dot_gcp__asr__v2__pb2.GetPhraseSetRequest.SerializeToString,
            service_dot_gcp__asr__v2__pb2.PhraseSet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePhraseSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/UpdatePhraseSet',
            service_dot_gcp__asr__v2__pb2.UpdatePhraseSetRequest.SerializeToString,
            gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePhraseSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/DeletePhraseSet',
            service_dot_gcp__asr__v2__pb2.DeletePhraseSetRequest.SerializeToString,
            gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UndeletePhraseSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.speech.v2.Speech/UndeletePhraseSet',
            service_dot_gcp__asr__v2__pb2.UndeletePhraseSetRequest.SerializeToString,
            gcp_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
