# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from service import gcp_locations_pb2 as service_dot_gcp__locations__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service/gcp_locations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LocationsStub(object):
    """An abstract interface that provides location-related information for
    a service. Service-specific metadata is provided through the
    [Location.metadata][google.cloud.location.Location.metadata] field.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListLocations = channel.unary_unary(
                '/google.cloud.location.Locations/ListLocations',
                request_serializer=service_dot_gcp__locations__pb2.ListLocationsRequest.SerializeToString,
                response_deserializer=service_dot_gcp__locations__pb2.ListLocationsResponse.FromString,
                _registered_method=True)
        self.GetLocation = channel.unary_unary(
                '/google.cloud.location.Locations/GetLocation',
                request_serializer=service_dot_gcp__locations__pb2.GetLocationRequest.SerializeToString,
                response_deserializer=service_dot_gcp__locations__pb2.Location.FromString,
                _registered_method=True)


class LocationsServicer(object):
    """An abstract interface that provides location-related information for
    a service. Service-specific metadata is provided through the
    [Location.metadata][google.cloud.location.Location.metadata] field.
    """

    def ListLocations(self, request, context):
        """Lists information about the supported locations for this service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocation(self, request, context):
        """Gets information about a location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLocations,
                    request_deserializer=service_dot_gcp__locations__pb2.ListLocationsRequest.FromString,
                    response_serializer=service_dot_gcp__locations__pb2.ListLocationsResponse.SerializeToString,
            ),
            'GetLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocation,
                    request_deserializer=service_dot_gcp__locations__pb2.GetLocationRequest.FromString,
                    response_serializer=service_dot_gcp__locations__pb2.Location.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.cloud.location.Locations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('google.cloud.location.Locations', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Locations(object):
    """An abstract interface that provides location-related information for
    a service. Service-specific metadata is provided through the
    [Location.metadata][google.cloud.location.Location.metadata] field.
    """

    @staticmethod
    def ListLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.location.Locations/ListLocations',
            service_dot_gcp__locations__pb2.ListLocationsRequest.SerializeToString,
            service_dot_gcp__locations__pb2.ListLocationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.cloud.location.Locations/GetLocation',
            service_dot_gcp__locations__pb2.GetLocationRequest.SerializeToString,
            service_dot_gcp__locations__pb2.Location.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
